### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by StefanGIT** [labbit-eu/transport_tools#2]
Hello,
i tried to install the transport_tools python package the following way (we do have a python module on our cluster):

module load Python-bundle-PyPI/2023.10-GCCcore-13.2.0

```
python3 -m venv ttool
source ttool/bin/activate
pip install --upgrade pip
 pip install transport_tools
python ttool/lib/python3.11/site-packages/transport_tools/scripts/tt_engine.py 


```

Doing so, i get the following error:

```
python ttool/lib/python3.11/site-packages/transport_tools/scripts/tt_engine.py 
Traceback (most recent call last):
  File "/home/richtesn/ttool/lib/python3.11/site-packages/transport_tools/scripts/tt_engine.py", line 24, in <module>
    from transport_tools.libs.tools import TransportProcesses, save_checkpoint, load_checkpoint
  File "/home/richtesn/ttool/lib/python3.11/site-packages/transport_tools/libs/tools.py", line 34, in <module>
    from transport_tools.libs.networks import TunnelNetwork, AquaductNetwork, SuperCluster, define_filters, TunnelCluster, \
  File "/home/richtesn/ttool/lib/python3.11/site-packages/transport_tools/libs/networks.py", line 35, in <module>
    from transport_tools.libs.geometry import Point, LayeredRepresentationOfTunnels, \
  File "/home/richtesn/ttool/lib/python3.11/site-packages/transport_tools/libs/geometry.py", line 27, in <module>
    import hdbscan
  File "/home/richtesn/ttool/lib/python3.11/site-packages/hdbscan/__init__.py", line 1, in <module>
    from .hdbscan_ import HDBSCAN, hdbscan
  File "/home/richtesn/ttool/lib/python3.11/site-packages/hdbscan/hdbscan_.py", line 9, in <module>
    from sklearn.base import BaseEstimator, ClusterMixin
  File "/home/richtesn/ttool/lib/python3.11/site-packages/sklearn/__init__.py", line 83, in <module>
    from .base import clone
  File "/home/richtesn/ttool/lib/python3.11/site-packages/sklearn/base.py", line 19, in <module>
    from .utils import _IS_32BIT
  File "/home/richtesn/ttool/lib/python3.11/site-packages/sklearn/utils/__init__.py", line 22, in <module>
    from ._param_validation import Interval, validate_params
  File "/home/richtesn/ttool/lib/python3.11/site-packages/sklearn/utils/_param_validation.py", line 15, in <module>
    from .validation import _is_arraylike_not_scalar
  File "/home/richtesn/ttool/lib/python3.11/site-packages/sklearn/utils/validation.py", line 24, in <module>
    from numpy.core.numeric import ComplexWarning  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'ComplexWarning' from 'numpy.core.numeric' (/home/richtesn/ttool/lib/python3.11/site-packages/numpy/core/numeric.py)

```

How can i solve the issue?

Kind regards

**Comment by briza81** [comment]
Hi @StefanGIT,

Thanks for the detailed report.  The failure comes from stale dependency metadata in the released version, which dates from early 2023 (before NumPy 2.0 existed). Its dependency pins only specify lower bounds, so pip installs NumPy 2.x — but the scikit-learn that 0.9.5 relies on still does `from numpy.core.numeric import ComplexWarning`, and NumPy 2.0 removed that symbol (it moved to `numpy.exceptions`). Hence the ImportError, which surfaces via hdbscan → sklearn before our code even loads.

We are completing the next release (much faster, and with more features0, but for now you have two quick fixes:

Option 1: stay with 0.9.5  which should work with your current Python 3.11

Just constrain NumPy back to the 1.x line in your existing venv, something like:

source ttool/bin/activate
pip install "numpy<2"


or rebuilt from scratch:

module load Python-bundle-PyPI/2023.10-GCCcore-13.2.0
python3 -m venv ttool && source ttool/bin/activate
pip install --upgrade pip
pip install "transport_tools==0.9.5" "numpy<2"

---
Option 2: try the current development version from `main`.  The code on `main` is already fixed for NumPy 2.x, but it requires **Python ≥ 3.12**, so you'll need to load a newer Python module than the 2023.10 bundle (which is 3.11):
---


Let me know if either route gives you trouble!

**Comment by StefanGIT** [comment]
Thanks,
i chose Option 1, but in addition i had to restrict biopython to < 1.80 to avoid an error there:

pip install "transport_tools==0.9.5" "numpy<2" "biopython<1.80"

Stefan
